### ISSUE TITLE
Remove dependency on `nflscrapR-data` and include `R` scripts to scrape the data independently

### ISSUE THREAD

**Issue by clausherther** [clausherther/nfl-dbt#4]
The `nflscrapR-data` repo is updated with some regularity, but since this is a voluntary and free resource, we can't rely on play data being updated weekly.

**Comment by bbrewington** [comment]
Also, `nflscrapR` is no longer maintained, and the owner suggested package `nflfasR` as a replacement: https://twitter.com/nflscrapR/status/1305586160262152193?s=20&t=AXsTQ754boe-VMxXjP5HdQ

Package info here: https://www.nflfastr.com/

**Comment by bbrewington** [comment]
probably best way to get the data is to use NFL data is released here: https://github.com/nflverse/nflverse-data/releases

**Comment by clausherther** [comment]
Closed via #8!
